export const AUTH_USER = '/fmb/action/AUTH_USER';
export const AUTH_ERROR = '/fmb/action/AUTH_ERROR';
export const API_USER_ERROR = '/fmb/action/API_USER_ERROR';
export const API_SERVER_ERROR = '/fmb/action/API_SERVER_ERROR';
export const GET_SUBSCRIBER_SCHEDULE = '/fmb/action/GET_SUBSCRIBER_SCHEDULE';
export const EDIT_SUBSCRIBER_SCHEDULE = '/fmb/action/EDIT_SUBSCRIBER_SCHEDULE';
export const ADD_SUBSCRIBER_OVERRIDESCHEDULE =
  '/fmb/action/ADD_SUBSCRIBER_OVERRIDESCHEDULE';
export const GET_SUBSCRIBER_OVERRIDESCHEDULE =
  '/fmb/action/GET_SUBSCRIBER_OVERRIDESCHEDULE';
export const EDIT_SUBSCRIBER_OVERRIDESCHEDULE =
  '/fmb/action/EDIT_SUBSCRIBER_OVERRIDESCHEDULE';
export const DELETE_SUBSCRIBER_OVERRIDESCHEDULE =
  '/fmb/action/DELETE_SUBSCRIBER_OVERRIDESCHEDULE';
export const FETCH_USER_PROFILE = '/fmb/action/FETCH_USER_PROFILE';
export const UPDATE_USER_PROFILE = '/fmb/action/UPDATE_USER_PROFILE';
export const GET_SCHEDULE_MONTHLY = '/fmb/action/GET_SCHEDULE_MONTHLY';
